### ISSUE TITLE
It doesn't work with Alecto WS-5500

### ISSUE THREAD

**Issue by pjmpessers** [AdyRock/com.weatherunderground#1]
Thank you for the great app. It sounds great if it worked with my Alecto WS-5500 (I think it is the same as Ambient WS-2902), but it doesn't. With WS view on my android phone i connected Alecto to wifi and in weather underground under devices. There i see that Alecto is online and i see the weather conditions. I placed the ID and key in the weather underground app when i connect a device in homey, but i don't get a read out. Am i doing something wrong?

UPDATE:

It seems i solved the problem. I needed to enter the API key.

Thank you for the great APP. I will buy you a beer. ;-)

**Comment by AdyRock** [comment]
I glad you found the issue and thanks for the update.
