### ISSUE TITLE
Missing uv and sun radiation 

### ISSUE THREAD

**Issue by pjmpessers** [AdyRock/com.weatherunderground#10]
Hello Ady.

I'm missing solar radiation and uv. I see them in the log but not in the app. Can you help me?

![Screenshot_20200714-220906_Homey](https://user-images.githubusercontent.com/34476404/87471668-0944a180-c61f-11ea-87a3-545d18911cbd.jpg)
![Screenshot_20200714-220734_Homey](https://user-images.githubusercontent.com/34476404/87471692-1366a000-c61f-11ea-8d0b-13fa8c04b13c.jpg)

**Comment by AdyRock** [comment]
My bad. The latest version removed those parameters if they are not reported. Unfortunately I should have checked for null as at the moment 0 is also considered missing. In theory the parameters should come back once you get values above 0.
But as that is not the desired outcome I have pushed a test version that should fix the problem. 
Let me know if its OK and I will request for it to be published.

**Comment by pjmpessers** [comment]
I go right on it. I let you know.

**Comment by pjmpessers** [comment]
Great. Ii's back. It works again on te 2.0.2 version. Thanks
