### ISSUE TITLE
Problem homety Pro Weather Underground

### ISSUE THREAD

**Issue by Waterman67** [AdyRock/com.weatherunderground#110]
Im ade a diagnostic log. The code to retrieve is this ? e76e32f0-ce00-41f3-a256-5cf783604dd4

After a few years the app didn.t communicate. The api key was expired. I generated a new key but this is not working. Removed the app and installed it again. Also did not work. 
This is the weather underground line from today. It says it is online and it is working.
![image](https://github.com/AdyRock/com.weatherunderground/assets/151658378/fbd685ce-059a-4e64-984d-92115e8c59a0)
![image](https://github.com/AdyRock/com.weatherunderground/assets/151658378/2759a5d7-0bf8-4c4f-9838-4c4b2e84e0cc)

Uploading a new api key ( number 3 or 4 !! then says this devices is not available ?

**Comment by SasquatchGER** [comment]
Ich have the same problem. Log in the Homey WU app: 
* Weather Refresh: GetURL Error: 401, Unauthorized

My PWS is online in WU and is working. I can see the data in the WU App. Station-ID and key is correct. I use a Homey PRO (early 2019).

**Comment by AdyRock** [comment]
Make sure you copy and paste the API Key as an incorrect key is the only thing that would give the unauthorised message.

When I connect to @Waterman67 station ID with my API key, I get error 204 no data. That means the weather station is not reporting to WU.

**Comment by SasquatchGER** [comment]
The station is online in WU, so station-ID and API key are correct, see screnshot:
![grafik](https://github.com/AdyRock/com.weatherunderground/assets/159390308/52efaf72-32cf-4e87-9da9-a50e8c011cdf)

Looks like the API key may not be transmitted - even if it is entered in the app:
![Screenshot_20240208_120801_Homey](https://github.com/AdyRock/com.weatherunderground/assets/159390308/530feb87-f6b1-4b61-8889-439f43ac5eb1)

**Comment by AdyRock** [comment]
The API key is not written to the Log for security reasons as I don't put anything in there that is secret.
Your station ID is public knowledge and can be looked in WU, so I can use my API key to view the data from your station or anyone else's station.

Basically, the API key is the only form of validation, so Error 401 can only be caused by that.

**Comment by SasquatchGER** [comment]
The WU PWS station ID is: **IWITTE156**
The station has only been around for a few days. In WU it is only visible when I log in to my personal profile. I can't (yet) find it using the station search in WU directly. Could this be the reason for the error?

**Comment by SasquatchGER** [comment]
OK, thanks for the tip. The error has been found, the app works.
