### ISSUE TITLE
sinds nieuwe homey problemen

### ISSUE THREAD

**Issue by jaccsnl** [AdyRock/com.weatherunderground#111]
Sinds mijn nieuwe Homey Pro heb ik problemen.
Er kan geen verbinding meer gemaakt worden met WU.
Apparaat en App weg gehaald, Homey opnieuw opgestart en geprobeert opnieuw te installeren/koppelen.

Nu kom ik niet verder als het invoeren van de ID + API Key. Deze kan ik prima vinden bij WU (zie ID: https://www.wunderground.com/weather/nl/nieuw-vennep/INIEUWVE47), maar Homey blijft aangeven geen verbinding te kunnen maken..

**Comment by Waterman67** [comment]
Bij mij precies hetzelfde probleem. Wel een weather underground abonnement maar geen verbinding kunnen krijgen.

**Comment by Willempy** [comment]
Hier hetzelfde probleem. Ik weet zeker dat stationID en api key kloppen, die werken namelijk wel in Domoticz

**Comment by jaccsnl** [comment]
De oplossing bij mij is alleen te werken met de apparatuur van Ziggo. 

Eerst had ik achter de router van Ziggo een eigen Synology router en die van Ziggo ingesteld als 'dom' modem. Werkte altijd met oudere Homey, maar niet met Homey Pro 2023. Inmiddels alleen apparatuur van Ziggo, nu werkt alles weer prima.
