### ISSUE TITLE
Problem with wind figures

### ISSUE THREAD

**Issue by gvdlooihoz** [AdyRock/com.weatherunderground#113]
Hi,
Yesterday I installed my Ventura W830 weather station and connected it to Weather Underground. All values in Weather Underground match the ones on my display. 
when I connected the Wunderground Homey app, I noticed that all values match more or less, but the values for wind and wind gust are way too low.
Current wind outside is now 24.1 km/h. They Homey app shows 6.69 km/h.
Is this a known issue or do I have to configure some settings?
I put the measures on all platforms to km/h.

thanks for your help and the great app!

**Comment by Homey4Osty** [comment]
Hi,
my values at the app are correct. It seams to be, that you only have a wrong setting ... cause 24,1 km/h are nearly 6,69 m/s
![image](https://github.com/AdyRock/com.weatherunderground/assets/146454771/b907710b-1133-4892-bdd8-8673eee4ac0c)

Change the units at the homey-app to km/h ... 

Is this the "problem"?

**Comment by gvdlooihoz** [comment]
Thanks for the help! The setting was at km/h so I never changed it.
Now i first changed it to m/s and after back to km/h and now the values are more like it.
So maybe a tiny initialization bug, but easy to work around.
Thanks for the help and all the good work!

**Comment by gvdlooihoz** [comment]
By the way, for sailors like me it would be a nice addition to also add knots as a possible measure for wind speed.

**Comment by AdyRock** [comment]
Knots are now added to the test version. Just add /test to the end of the app URL in the store to install it.

**Comment by gvdlooihoz** [comment]
You are brilliant
