### ISSUE TITLE
Poll interval

### ISSUE THREAD

**Issue by slasktrat** [AdyRock/com.weatherunderground#14]
Hi. Thanks for this great app! 

I've been a happy user for months, but a couple of days ago I installed a weather station on a second location and installed this app om my second Homey. But then both integrations stopped working after short time as number of free api calls are constantly exceeded. 

So it would be very useful if the poll interval could be configurable.

**Comment by AdyRock** [comment]
I will have a look. 
Although, could you create two WU accounts, one for each weather station? Then you would still get the maximum update rate.

**Comment by slasktrat** [comment]
I considered to create a second wu account, but do not need 60 second update rate and creating a second wu account would also actually break the eula.

**Comment by AdyRock** [comment]
I have published a new test version. This has an option in the Configure App section to specify the number of stations on your account. The timer then multiplies the interval by the number of stations. So 1 station is 1 minute, 2 stations is 2 minutes, etc.

**Comment by slasktrat** [comment]
Perfect, thank you! 👍😊
