### ISSUE TITLE
Weather Underground PWS app Km/h = m/s

### ISSUE THREAD

**Issue by paaccoo** [AdyRock/com.weatherunderground#15]
Hi, 
I noticed lately that the info for Wind Strength and Gust Strength from my Weather Station, where not correct anymore, in the Homey app.
Strength and Gust Strength are in Km/h, on my Weather Station, Weather Underground, on my telephone (android app) and on HOMEY.  
I found out that the values on Homey are NOT Km/h, but M/S.
In the past this was not the case, and the indication were correct in Km/h.
I did not find a way to change this (Km/h to m/s) in the Homey app.
Possible solution? 

ps

Thanks for writing the app !!

**Comment by AdyRock** [comment]
There is an option in the Configure App section. 
It should default to Km/H so I will look in to that.

**Comment by paaccoo** [comment]
Update, 
After changing several times between km/h and m/s (Homey App → More → Apps → Weather Underground → Configure app → Units: Wind speed (choose m/s) → Save changes - and the same for Km/h), the data in the Homey app is now (again) in real Km/h. 
So, I am happy.
Sorry for all the fuss.
Thanks again.
