### ISSUE TITLE
GetURL Error: 401, Unauthorized

### ISSUE THREAD

**Issue by MarcelFrensch** [AdyRock/com.weatherunderground#16]
Hi AdyRock,

I've sometimes the following error: GetURL Error: 401, Unauthorized (see screenshot below)
As far as I know this error only happens in the evening (not every day)

The weather station is an WS-5500 and I think the problem occurred after I connected the weather station to a second Homey.

What I tried so far:
- PtP (Both Homeys)
- Restart App
- Remove device from 1 Homey
- checked connection WS-5500 with Weather Underground (No connection problem, see screenshot below- same time as error) 
- Renew API key
- Checked the version -> Latest version.

I Hope you can help me, thanks in advance.

Best regards, 
Marcel Frensch

![Screenshot_20210705-222239_Homey](https://user-images.githubusercontent.com/87002598/124553743-668bc100-de35-11eb-9b58-097ff9724c39.jpg)

![Screenshot_20210705-222246_Homey](https://user-images.githubusercontent.com/87002598/124553762-6e4b6580-de35-11eb-992e-e573f9eede52.jpg)

![Screenshot_20210705-222319_WS View](https://user-images.githubusercontent.com/87002598/124553774-71465600-de35-11eb-8a7d-f83e31d6430e.jpg)

**Comment by AdyRock** [comment]
WU has a limit on the number of calls to get data and I think with two Homey's it is exceeding that rate.
Have you changed the settings in the Apps - Weather Underground - Configure App on both Homey's to specify you have two devices connecting?
![Screenshot_20210706-094520_Homey](https://user-images.githubusercontent.com/38184396/124571067-609add80-de3f-11eb-8d3c-81fe65f39ce3.jpg)

**Comment by AdyRock** [comment]
I have just noticed the wording in the page might be wrong. It mentions stations but that should be devices that get data.

**Comment by MarcelFrensch** [comment]
I didn't change the number of Stations (devices) 
I will change this is both Homey to 2 and I will hope that will be the solution.

Thanks! I will let you know if it works.

**Comment by MarcelFrensch** [comment]
Hi AdyRock,

I forget to give you the feedback, but it works! 

I changed the number of Stations on both Homey's to 2 and it works perfectly.

Thanks for your help!

Best regards,
Marcel
