### ISSUE TITLE
Error in app - app not working

### ISSUE THREAD

**Issue by mcrbrauers** [AdyRock/com.weatherunderground#19]
The app is not working at all.

There is a stabile connecion with WU, but the Homey can't get de info via the API. 

the app is showing error:   GetURL On Error: Client Network socket disconnected before secure TLS connection was estalished.

==============
Copy of the log:

App Started
2022-01-12T15:00:04.686Z
  * https://api.weather.com/v2/pws/observations/current?numericPrecision=decimal&stationId=IHOOFD63&format=json&units=m&apiKey=

2022-01-12T15:01:02.735Z
  * GetURL On Error: Client network socket disconnected before secure TLS connection was established
Error: Client network socket disconnected before secure TLS connection was established
    at connResetException (internal/errors.js:604:14)
    at TLSSocket.onConnectEnd (_tls_wrap.js:1513:19)
    at Object.onceWrapper (events.js:417:28)
    at TLSSocket.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

2022-01-12T15:01:02.741Z
  * Weather Refresh: GetURL On Error: Client network socket disconnected before secure TLS connection was established

2022-01-12T15:01:08.670Z
  * https://api.weather.com/v3/wx/forecast/daily/5day?placeid=006c3203c2ec067f18e966af6ad60ecce6f0d284f3a0d0a5badd8043ae7fefa3&units=m&language=nl-NL&format=json&apiKey=

2022-01-12T15:01:08.695Z
  * https://api.weather.com/v3/wx/forecast/daily/5day?placeid=006c3203c2ec067f18e966af6ad60ecce6f0d284f3a0d0a5badd8043ae7fefa3&units=m&language=nl-NL&format=json&apiKey=

2022-01-12T15:01:54.944Z
  * GetURL On Error: Client network socket disconnected before secure TLS connection was established
Error: Client network socket disconnected before secure TLS connection was established
    at connResetException (internal/errors.js:604:14)
    at TLSSocket.onConnectEnd (_tls_wrap.js:1513:19)
    at Object.onceWrapper (events.js:417:28)
    at TLSSocket.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

2022-01-12T15:01:54.953Z
  * Forecast Refresh: GetURL On Error: Client network socket disconnected before secure TLS connection was established

2022-01-12T15:01:54.967Z
  * GetURL On Error: Client network socket disconnected before secure TLS connection was established
Error: Client network socket disconnected before secure TLS connection was established
    at connResetException (internal/errors.js:604:14)
    at TLSSocket.onConnectEnd (_tls_wrap.js:1513:19)
    at Object.onceWrapper (events.js:417:28)
    at TLSSocket.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

2022-01-12T15:01:54.973Z
  * Forecast Refresh: GetURL On Error: Client network socket disconnected before secure TLS connection was established

2022-01-12T15:02:02.785Z
  * https://api.weather.com/v2/pws/observations/current?numericPrecision=decimal&stationId=IHOOFD63&format=json&units=m&apiKey=

2022-01-12T15:02:55.148Z
  * GetURL On Error: Client network socket disconnected before secure TLS connection was established
Error: Client network socket disconnected before secure TLS connection was established
    at connResetException (internal/errors.js:604:14)
    at TLSSocket.onConnectEnd (_tls_wrap.js:1513:19)
    at Object.onceWrapper (events.js:417:28)
    at TLSSocket.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

2022-01-12T15:02:55.151Z
  * Weather Refresh: GetURL On Error: Client network socket disconnected before secure TLS connection was established

2022-01-12T15:03:55.249Z
  * https://api.weather.com/v2/pws/observations/current?numericPrecision=decimal&stationId=IHOOFD63&format=json&units=m&apiKey=
================

Please fix the app!!!

**Comment by AdyRock** [comment]
That's a low level error so the only thing I can suggest is to reboot things.

**Comment by mcrbrauers** [comment]
Every setting reset en reinstalled.Works for one day!!Please fix the app. I tuin the problem starts after the latest update.Please fix the app. This is worthless!!
-------- Oorspronkelijk bericht --------Van: Adrian Rockall ***@***.***> Datum: 12-01-2022  17:32  (GMT+01:00) Aan: "AdyRock/com.weatherunderground" ***@***.***> Cc: mcrbrauers ***@***.***>, Author ***@***.***> Onderwerp: Re: [AdyRock/com.weatherunderground] Error in app - app not working (Issue #19) 
That's a low level error so the only thing I can suggest is to reboot things.

**Comment by mcrbrauers** [comment]
Please fix the app!See attachement
-------- Oorspronkelijk bericht --------Van: Adrian Rockall ***@***.***> Datum: 12-01-2022  17:32  (GMT+01:00) Aan: "AdyRock/com.weatherunderground" ***@***.***> Cc: mcrbrauers ***@***.***>, Author ***@***.***> Onderwerp: Re: [AdyRock/com.weatherunderground] Error in app - app not working (Issue #19) 
That's a low level error so the only thing I can suggest is to reboot things.

**Comment by AdyRock** [comment]
Unfortunately GitHub does not process the email attachments so they just get lost. If you have some information then you will need to paste it into the message.
If the error is the same as before then I don't know how to fix it as it is a low level network error.
There are currently 800 users on the new version and you are the only one reporting this error so I don't have enough information to even suggest what the problem might be.
Could you provide information about your Homey such as model, firmware version, etc, so i can ask Athom if they have any suggestions.

**Comment by AdyRock** [comment]
Could you check your router configuration to make sure it doesn't have any firewall options that could be blocking the access.

**Comment by Joolee** [comment]
@mcrbrauers Might I recommend you show some respect to the developer? He provides this app free of charge, doesn't even have a donate button and still responds to you within a day to help you fix a problem that's probably not even his fault!

If it was me, I would have send you a quote for my hourly rate with that attitude.

**Comment by mcrbrauers** [comment]
> @mcrbrauers Might I recommend you show some respect to the developer? He provides this app free of charge, doesn't even have a donate button and still responds to you within a day to help you fix a problem that's probably not even his fault!
> 
> If it was me, I would have send you a quote for my hourly rate with that attitude.

Fuck you asshole
