### ISSUE TITLE
is it possible to display the temperature 1 digit after the comma?

### ISSUE THREAD

**Issue by pjmpessers** [AdyRock/com.weatherunderground#2]
On this moment the temperature is a round number on homey. is it possible to display the temperature 1 digit after the comma?

Thanks.

**Comment by AdyRock** [comment]
I will have a look tonight. I think there is a way to ask WU for more decimals.

**Comment by pjmpessers** [comment]
Thank you. Great. I will wait for the update. :-)


-------- Oorspronkelijk bericht --------
Van: AdyRock <notifications@github.com>
Datum: 03-03-2020 10:08 (GMT+01:00)
Aan: "AdyRock/com.weatherunderground" <com.weatherunderground@noreply.github.com>
Cc: Pieter <pieterpessers@hotmail.com>, Author <author@noreply.github.com>
Onderwerp: Re: [AdyRock/com.weatherunderground] is it possible to display the temperature 1 digit after the comma? (#2)


I will have a look tonight. I think there is a way to ask WU for more decimals.

**Comment by pjmpessers** [comment]
Hello Adyrock.
Thank you for the new update. I get my temperature and many other readings in one digit after the comma. (Decimal). But it lost the air pressure.
Could you look into that?
Thanks.

**Comment by pjmpessers** [comment]
sorry. Update. Sometimes it gets a pressure readout. But going out of the weather station readout and back in it lost that readout.

**Comment by AdyRock** [comment]
Are you getting the code from GitHub? If so can you try again.
It maybe you were a bit premature in getting it as I have only just finished it.
I was also adding UV so it maybe you got part of that but not all of it.

**Comment by pjmpessers** [comment]
Yes. Is sideloaded it.

I will try the new one.

Verzonden vanuit Mail<https://go.microsoft.com/fwlink/?LinkId=550986> voor Windows 10

________________________________
Van: AdyRock <notifications@github.com>
Verzonden: Tuesday, March 3, 2020 6:23:49 PM
Aan: AdyRock/com.weatherunderground <com.weatherunderground@noreply.github.com>
CC: Pieter <pieterpessers@hotmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [AdyRock/com.weatherunderground] is it possible to display the temperature 1 digit after the comma? (#2)


Are you getting the code from GitHub? If so can you try again.
It maybe you were a bit premature in getting it as I have only just finished it.
I was also adding UV so it maybe you got part of that but not all of it.

**Comment by pjmpessers** [comment]
I don’t have a readout now for 2 hours. But maybe this fault is on my side. Maybe i looked to much into it. And this way i did it more then 1500 times. And i connected weather underground by somebodies else homey as well. And me and his homey combined it was more readouts then allowed. I will try it tommorow.

I did see a new UV-readout.

For now i want to thank you for your quick responce.

Verzonden vanuit Mail<https://go.microsoft.com/fwlink/?LinkId=550986> voor Windows 10

Van: AdyRock<mailto:notifications@github.com>
Verzonden: dinsdag 3 maart 2020 18:23
Aan: AdyRock/com.weatherunderground<mailto:com.weatherunderground@noreply.github.com>
CC: Pieter<mailto:pieterpessers@hotmail.com>; Author<mailto:author@noreply.github.com>
Onderwerp: Re: [AdyRock/com.weatherunderground] is it possible to display the temperature 1 digit after the comma? (#2)


Are you getting the code from GitHub? If so can you try again.
It maybe you were a bit premature in getting it as I have only just finished it.
I was also adding UV so it maybe you got part of that but not all of it.

**Comment by AdyRock** [comment]
I sometimes have the same problem of using all my reads when I am testing.
You can see how many hits you have made on the WU page for your API key by clicking on the API Key Usage buton.

**Comment by pjmpessers** [comment]
Thank you for the tip.

Clicking it and it said:” Usage data could not be retrieved. Undefined”

Verzonden vanuit Mail<https://go.microsoft.com/fwlink/?LinkId=550986> voor Windows 10

Van: AdyRock<mailto:notifications@github.com>
Verzonden: dinsdag 3 maart 2020 20:24
Aan: AdyRock/com.weatherunderground<mailto:com.weatherunderground@noreply.github.com>
CC: Pieter<mailto:pieterpessers@hotmail.com>; Author<mailto:author@noreply.github.com>
Onderwerp: Re: [AdyRock/com.weatherunderground] is it possible to display the temperature 1 digit after the comma? (#2)


I sometimes have the same problem of using all my reads when I am testing.
You can see how many hits you have made on the WU page for your API key by clicking on the API Key Usage buton.

**Comment by pjmpessers** [comment]
After a few ettempts i got a api key usage readout. It seems i used it more then 1500. I think because i made the mistake for a second homey to read the data of my station. So i think the problem is not your app. I will let you know it it works again tomorow.

**Comment by pjmpessers** [comment]
After 00.00 hours it is collecting data again. And the pressure works again. And as bonus i also have a UV reading.

So i'm very happy with this app.

Thanks.

**Comment by AdyRock** [comment]
Excellent I will close this off now then.

P.S. If you are interested I have now added a new device to the app for "Tomorrows" weather forecast.
