### ISSUE TITLE
Error 204

### ISSUE THREAD

**Issue by jaccsnl** [AdyRock/com.weatherunderground#20]
Getting error 204: no data found..

No idea why, used to work perfect..?

working with homey 2019 and triple checked the API code of WU

**Comment by AdyRock** [comment]
Error 204 means the weather station hasn't sent any data to WU for over an hour. It is the error message return by WU when that happens. So, it not a problem with Homey or the app but with the weather station.
Can you check on the WU website to see if that is showing up to date data from your weather station?

**Comment by jaccsnl** [comment]
Hi Adrian,

This is my weather station: https://www.wunderground.com/weather/INIEUWVE47

Seems it works fine, and no wit also works fine in Homey..

I’ll check this (better) next time 😉

Met vriendelijke groet,

Roeland van Anholt
JACCS

***@***.***



***@***.***

Faustlaan 72
2152 PJ  Nieuw-Vennep

T 0252-258161
M 06-37083432

website<https://jaccs.nl> | LinkedIn<https://www.linkedin.com/company/jaccs> | nieuwsbrief<https://jaccs.nl/nieuwsbrief> | account<https://jaccs.nl/account> | kaart<https://www.google.nl/maps/place/JACCS> | contact<https://jaccs.nl/contact>



Van: Adrian Rockall ***@***.***>
Verzonden: maandag 18 april 2022 15:49
Aan: AdyRock/com.weatherunderground ***@***.***>
CC: JACCS Support ***@***.***>; Author ***@***.***>
Onderwerp: Re: [AdyRock/com.weatherunderground] Error 204 (Issue #20)


Error 204 means the weather station hasn't sent any data to WU for over an hour. It is the error message return by WU when that happens. So, it not a problem with Homey or the app but with the weather station.
Can you check on the WU website to see if that is showing up to date data from your weather station?

**Comment by AdyRock** [comment]
There is a flow trigger card in the app for "No data has been received" and I use that to notify me when the station has stopped sending data. Then I reboot the station or WiFi if required.

**Comment by jaccsnl** [comment]
Thanks for the tip! 😊

Met vriendelijke groet,

Roeland van Anholt
JACCS

***@***.***



***@***.***

Faustlaan 72
2152 PJ  Nieuw-Vennep

T 0252-258161
M 06-37083432

website<https://jaccs.nl> | LinkedIn<https://www.linkedin.com/company/jaccs> | nieuwsbrief<https://jaccs.nl/nieuwsbrief> | account<https://jaccs.nl/account> | kaart<https://www.google.nl/maps/place/JACCS> | contact<https://jaccs.nl/contact>



Van: Adrian Rockall ***@***.***>
Verzonden: dinsdag 19 april 2022 09:24
Aan: AdyRock/com.weatherunderground ***@***.***>
CC: JACCS Support ***@***.***>; Author ***@***.***>
Onderwerp: Re: [AdyRock/com.weatherunderground] Error 204 (Issue #20)


There is a flow trigger card in the app for "No data has been received" and I use that to notify me when the station has stopped sending data. Then I reboot the station or WiFi if required.
