### ISSUE TITLE
App needs restarting once in a while

### ISSUE THREAD

**Issue by abra03brand** [AdyRock/com.weatherunderground#21]
Hi there,

I have to restart the app every week to make sure actual information keeps flowing in. 

I made a log for you: 3f9b75cc-ba9c-4cdb-91b2-7d78a8c78016

I hope you can help me out. 
kind regards, André

**Comment by AdyRock** [comment]
Unfortunately, the log is not showing any issues.
When it stops updating again, could you send a log from the app (https://tools.developer.homey.app/tools/app-settings) before you restart the app.
You will probably need to enable the log first (blue tick) and then wait for a while so the app has a chance to poll for data, although it may contain error message when you go there.
