### ISSUE TITLE
Weather Underground Homey pro

### ISSUE THREAD

**Issue by Meki1984** [AdyRock/com.weatherunderground#22]
Hello Adrian

I buyed my homey pro in the end of May, so I’m very new in the Homey community.

My aim is to use my private weather station as a controll unit, especially the watts per m2 unit, as a controller for my shutters.

A friend of my told me, I have write you in case of I need the watts per m2 in a AND condition. So is it possible to add this function in the app , or you have a solution how can I circumnavigate this point?

Many thanks in advance.

BR 

 Marius

**Comment by AdyRock** [comment]
You can use the Logic card and select the solar from there 
![Screenshot_20220601-212310_Homey](https://user-images.githubusercontent.com/38184396/171494999-ced10a8b-a905-4b45-84ce-dbd876de58f8.jpg)
![Screenshot_20220601-212333_Homey](https://user-images.githubusercontent.com/38184396/171495064-2d148ee7-cbe7-4bc7-8cdd-0a31dfa480ff.jpg)
![Screenshot_20220601-212359_Homey](https://user-images.githubusercontent.com/38184396/171495095-761a8053-7821-46b4-b224-b9f3d28ef8ad.jpg)

**Comment by Meki1984** [comment]
Hello 

thanks for the fast reply. 

Yes, I have this kind of fields and can select the relevant numbers I need. Many thanks thanks, that will help.

BR
