### ISSUE TITLE
homey app for Ecowitt 

### ISSUE THREAD

**Issue by fhutter** [AdyRock/com.weatherunderground#24]
At first sorry I didn‘t found the right repository, so I taken this one.

I can‘t add any devices with Ecowitt App for homey. The listening Port is 7777

also I Set The Sending Port in ws view to 7777. the server IP is the Local IP of homey. Protocol is ecowitt. Path is empty. And for Sure it is enabled.

i think I have done everything right but I am not sure. The default upload to ecowitt with mac Adress a.s.o works without any problems

**Comment by AdyRock** [comment]
The path should be '/data/report'
The instructions are listed in the Homey forum https://community.homey.app/t/app-pro-misol-and-ecowitt-version-0-1-10-and-test-0-1-13/47076

Also the repo for the Misol and Ecowitt, if you want to look at the code is https://github.com/AdyRock/com.misol

Hope that helps.
