### ISSUE TITLE
flow card and the AND option not working

### ISSUE THREAD

**Issue by valkhyr1** [AdyRock/com.weatherunderground#25]
With Homey v7.4.3 and weather underground app ver 3.0.9 I'm missing the weather underground options in the flow card and the AND option.
With only the IF option I can select the weather underground options.
![homey](https://user-images.githubusercontent.com/10817059/175777149-1a3d6600-5b22-473c-a6eb-869a03af067f.jpg)

**Comment by AdyRock** [comment]
You can use the logic cards and the tags from the app:
![image](https://user-images.githubusercontent.com/38184396/175779934-852e71da-c70e-49c6-b2ed-512da41b5fd6.png)

![image](https://user-images.githubusercontent.com/38184396/175779983-30070989-6cd0-4adc-8a9f-9fbb16b2dcce.png)


![image](https://user-images.githubusercontent.com/38184396/175779959-9b67a259-6d51-4b89-9a70-fdfe119ab4dc.png)

![image](https://user-images.githubusercontent.com/38184396/175780041-72b18283-fad0-4aba-98cd-c46175bb030f.png)

**Comment by AdyRock** [comment]
If you are using the forecast device then there are logic AND card so you can select the period:
![image](https://user-images.githubusercontent.com/38184396/175780126-c882b0ae-c969-4585-b836-b7459e888efa.png)

**Comment by valkhyr1** [comment]
[](url)

**Comment by valkhyr1** [comment]
Thanks for the quick response, I can use the logic cards and tags.
