### ISSUE TITLE
Stopped working after 2 days

### ISSUE THREAD

**Issue by eddiegonzales** [AdyRock/com.weatherunderground#26]
Hi,

I have been using Weather Underground for my Davis Vantage 2 Pro weather station for years and was excited to see that Homey Pro supports this. But now after running 2 days its not working any more. I have checked the station ID and the API key. I get the error: GetURL Error: 204, No Data Found

I have tried to delete and added it again. Didn't help. I have also checked my API usage and had a max of 731 request in 24 hours, so i am not near the limit from Weather Underground.

**Comment by AdyRock** [comment]
That error means your weather station is not sending data to Weather Underground.

**Comment by eddiegonzales** [comment]
Hi,

I also suspected that, and that is why i checked that before reporting the issue. Weather Underground says my station is online, and my weather station software runs Rapidfire and i can see that it is sending data every 3 seconds.

**Comment by AdyRock** [comment]
Is this your station?
![image](https://user-images.githubusercontent.com/38184396/191332012-775712f7-3a8e-445b-9ecd-86e491a91be0.png)

**Comment by eddiegonzales** [comment]
No. This one is mine. But the strange thing is on my station overview it says its online. On this view it says offline, and on the graph overview it has reported until now
<img width="1278" alt="image" src="https://user-images.githubusercontent.com/6574811/191332443-1f38a9e7-3955-4492-b232-1199e0e9037d.png">

**Comment by AdyRock** [comment]
I'm not sure if WU is having issue because I have had several logs sent in over the last week with the same error.

This is my ID IHORSH12 which is still working OK.

**Comment by stephanvalkaer** [comment]
It seems like they know of an issue: https://support.weather.com/s/?type=wu&language=en_US

**Comment by eddiegonzales** [comment]
Sorry. Replied with a wrong account. :-) I did link to their support page mentioning a problem with the PWS system

**Comment by eddiegonzales** [comment]
Seems to be working sporadically again

**Comment by AdyRock** [comment]
Thanks for the update, good to know in case other users have the problem.
