### ISSUE TITLE
Adding option for the homey pro 2023

### ISSUE THREAD

**Issue by KimdeJo** [AdyRock/com.weatherunderground#28]
Hello,

We've got the homey pro 2023 and an weather station that is linked to the Weather Underground app.
We really like using it.  We are using it in the advanced flow.

But we are missing some options, is it possible to add some options?
We are missing is 'an bigger than' option instead of 'an become bigger than' option.

Also that you can add carts in the  'and' function.  So you don't have to start with an option from the weather underground. 

I hope you understand it, let me know if you need more information.
I hope to hear from you. Thanks

Greetz, Kim

**Comment by AdyRock** [comment]
If it was a bigger than, then when would Homey trigger it. It would effectively be constantly triggering which would break the rules. 

You can use logic cards in the And section to compare global tags made available by the app. 

Hope that makes sense and I have got the correct meaning of your post.

**Comment by Homey4Osty** [comment]
Hello!
I'm also missing some options with the sunshine duration.
It would be nice if you can add this option at 'if' and/or 'and':
- expected sunshine today changed
- expected sunshine today (in h)
- expected sunshine tomorrow changed
- expected sunshine tomorrow (in h)
- expected sunshine day after tomorrow changed
- expected sunshine day after tomorrow  (in h)
- sunshine expected next hour
- sunshine expected in 2, 3, ... hours

Is it possible to add this options / features please?

Thanks a lot.

Greatings Osty

**Comment by AdyRock** [comment]
I can't see any sunshine data in the information returned from WU, so I'm afraid that will not be possible,

**Comment by Homey4Osty** [comment]
Sunshine is a low %-value of cloud cover. 

Are you getting hourly forecasts for today and tomorrow?
So, if you can add for both "and" - cards of "the cloud cover ..." a new "periode to report" with a day and time-slot (for example: Tomorow 11am -12 pm, 12pm - 1 pm, ... 

That would be enough and i can define and count the rest with an advanced flow myself ... 

thx again.
