### ISSUE TITLE
can't connect to my Ventus weatherstaition

### ISSUE THREAD

**Issue by MrFlash2023** [AdyRock/com.weatherunderground#29]
I cen't connect to my Ventus Weatherstation anymore
e9c3f874-7485-4406-b261-95d6e35c0193

App Started
2023-08-28T07:30:20.859Z
  * https://api.weather.com/v2/pws/observations/current?numericPrecision=decimal&stationId=INSTVE53&format=json&units=m&apiKey=

2023-08-28T07:30:21.232Z
  * Done retrieval of data

2023-08-28T07:30:21.236Z
  * HTTPS Error: 204

2023-08-28T07:30:21.239Z
  * Weather Refresh: GetURL Error: 204, No Data Found

**Comment by AdyRock** [comment]
The error that is being returned means you weather station has not published data to Weather Underground for 24 hours or more.
