### ISSUE TITLE
dutch translation

### ISSUE THREAD

**Issue by Raycokes2000** [AdyRock/com.weatherunderground#3]
Hello, i can not open pull request, so we open an issue, what needs to be translated to ducth. How can i help. 
Regards Ray

**Comment by AdyRock** [comment]
Thank you for your support. Below are the texts that I think need translation:

"Get the last data from you weather station"
"Weather"
"Climate"
"Forecast"
"Precipitation Type"
"Thunder"
"Precipitation Chance"
"Cloud Cover"
"Snow Total"
"Weather Station"
"Feels Like"
"Wind chill"
"Dew point"
"Rain Total"
"Station Details"
"Station ID"
"API Key"
"Weather Forecast"
"High Temperature"
"Low Temperature"
"Your Weather Underground Station Information."
"Add Station"
"Station ID is required"
"API Key is required"

If you could copy the list and then add the translation next to each one that would be great. I would use Google translations if I could trust them but I have found them unreliable in the past.

**Comment by Raycokes2000** [comment]
ok copy that, hereby translated, i understand what you are saying.
Anything else?

Regards Ray

"Get the last data from you weather station" "Haal de laatste gegevens van uw weerstation op"
"Weather" "Weer"
"Climate" "Klimaat"
"Forecast" "Verwachting"
"Precipitation Type" "Neerslagtype"
"Thunder" "Onweer"
"Precipitation Chance" "Neerslagkans"
"Cloud Cover" "Bewolking"
"Snow Total" "Sneeuwtotaal"
"Weather Station" "Weerstation"
"Feels Like" "Voelt als"
"Wind chill" "Gevoelstemperatuur"
"Dew point" "Dauwpunt"
"Rain Total" "Regen Totaal"
"Station Details" "Station detail informatie"
"Station ID" "Station ID"
"API Key" "API Sleutel"
"Weather Forecast" "Weersverwachting"
"High Temperature" "Hoge temperatuur"
"Low Temperature" "Lage temperatuur"
"Your Weather Underground Station Information." "Informatie over uw weerstation."
"Add Station" "Station toevoegen"
"Station ID is required" "Station ID is vereist"
"API Key is required" "API-sleutel is vereist"

**Comment by AdyRock** [comment]
That's great thank you. I will put them in this evening and publish another test version.

**Comment by pjmpessers** [comment]
Thank you very much for the Dutch translation, Adyrock and Raycokes2000.
There is one tiny translation that i think can be improved.
I think it is called "Wind force." in english. It is translated as "Windstoot kracht". But i think it is better as it's translated as "Windstoten".
Keep up the good work.

**Comment by Raycokes2000** [comment]
copy that, have not seen that one, but would be like just "windstoot"

**Comment by pjmpessers** [comment]
Your right. Windstoot would be better.

**Comment by AdyRock** [comment]
Hmm, Interesting as that is one of the built in capabilities so that text comes from Athom. In English it is "Wind Strength".

**Comment by AdyRock** [comment]
OK, the WU document says this for that parameter:

> The maximum forecasted wind speed.The wind is treated as a vector; hence, winds must have direction and magnitude (speed). The wind information reported in the hourly current conditions corresponds to a 10-minute average called the sustained wind speed. Sudden or brief variations in the wind speed are known as “wind gusts” and are reported in a separate data field. Wind directions are always expressed as "from whence the wind blows" meaning that a North wind blows from North to South. If you face North in a North wind the wind is at your face. Face southward and the North wind is at your back.

So it looks like I have picked the wrong capability. I will change that for the next update.

**Comment by pjmpessers** [comment]
Google translate is saying "wind gust" translation is "windvlaag". Maybe this is a better one.

**Comment by AdyRock** [comment]
I have changed the capability from measure_wind_strength to measure_gust_strength in the new version. They are built in capabilities so will use Athom's text. What does it display as in Dutch now?

**Comment by Raycokes2000** [comment]
on what screen, forecast or device?
i also see on device, wind direction arrow to north east saying 249 degrees NE would around eg 45degrees.

**Comment by AdyRock** [comment]
The Gust Strength is on both devices.
The arrow is a fixed graphic as it is not possible to change them at will. So it is just the number that changes. Again this is an Athom image for the built in capability.

**Comment by pjmpessers** [comment]
I think he is not talking about the graphic. But the wrong number in degrees.

**Comment by AdyRock** [comment]
The number is in theory what comes back from WU. Maybe you can confirm if the number you see in the app is the same or different to the number on WU. The angle given is the direction the wind is coming from. My WU and phone seem to agree as far as I can tell.

**Comment by pjmpessers** [comment]
Your right from wu point of view. They calculate the degrees counter clockwise. Starting a north as zero degrees. I thought did would be clockwise.

**Comment by pjmpessers** [comment]
Almost perfect translation from what i can see.
Only one thing. It is saying "Windstoot kracht". But in dutch it is not necessary to include "kracht - strength". Windstoot already suggest that there is strength (Force) in the wind. So "windstoot" would be enough. I think in English it is the same. Wind gust is enough. You don't have to include strength,

**Comment by AdyRock** [comment]
Thanks for confirming. I think I will leave the Athom standard translation for now and maybe see what they say.

**Comment by pjmpessers** [comment]
It is good enough. Great app by the way.

**Comment by Raycokes2000** [comment]
for now this can be closed, thanks all! good job!
