### ISSUE TITLE
Request for Solar radiation

### ISSUE THREAD

**Issue by pjmpessers** [AdyRock/com.weatherunderground#4]
Hello.

Sorry for my many requests. I like the app a lot.
But is it also possible to include solar radiation (Zonnesterkte - zonnestraling).
That would be great.

**Comment by AdyRock** [comment]
Yes, I can add that. My station doesn't have it so I missed that one as I did with the UV.

**Comment by pjmpessers** [comment]
Thank you, AdyRock

**Comment by AdyRock** [comment]
Do you see this on your WU page?
The API doesn't tell me what units it reports, it just say integer/decimal e.g. 92.0 so was hoping it might show the units on your page.

**Comment by pjmpessers** [comment]
I see it on my wu. And W/m2 is for the Solar radiation. So i think you are on the right path.

**Comment by AdyRock** [comment]
The solar radiation is in the new version.

**Comment by pjmpessers** [comment]
Thank you. Is it also in GITHUB? I only see the version from 11 hours ago.

**Comment by AdyRock** [comment]
I didn't have time to push it but I will do it when I get back home.

**Comment by pjmpessers** [comment]
Excellent. Thank you.

**Comment by AdyRock** [comment]
GitHub is now up to date.

**Comment by pjmpessers** [comment]
Again thank you very much. It looks that you nailed it. I see solar radiation (zonnestraling) in W/m2. But i can't be 100% sure if it is the right data, because it is night in the Netherlands.

**Comment by pjmpessers** [comment]
You nailed it. I get a read out. Thank you. Happy with it. 
Just one last thing. A little clean up. I think that feels like and feelingtemperature are the same thing with the same data.
Everything else is great.

**Comment by pjmpessers** [comment]
Strange. While all other data's is refreshing every minute, the data of solar radiation stayed the same for 20 minutes at homey. This while on the app "ws-view" it also changes.

**Comment by AdyRock** [comment]
Is it changing on WU ?
The app grabs all the data from WU in one big block and then extracts the individual fields so in theory all the data should be in sync. I will check if it's possible for it to bypass that field somehow today as soon as I can.

**Comment by pjmpessers** [comment]
It is changing on WU. Maybe it has to do with the graphic on there website. It has a graphic for solar radiation. When you go to the web browser. Hit "view page source" (translate from dutch) and then find on page you can look for solarradiation. And there are 108 of it. I think that has to do with the used graphic for there webside. I think it uses some treshhold. And maybe that is why it has a readout our not depending on which treshold it has. But i think you know it beter.

**Comment by pjmpessers** [comment]
I restarted your app and for Solar radiation there came data in. I only saw a "-" sign.
When night felt i got a a reading back of 0 W/m2

**Comment by pjmpessers** [comment]
It get it's data in ones and then some how blocked. Looking at the data you can see it is changing. (Removed some things)

https://api.weather.com/v2/pws/observations/current?numericPrecision=decimal&stationId=*********&format=json&units=m&apiKey=**********
* retrieve data
* Done retrieval of data
* currentData = {
  "stationID": "********",
  "obsTimeUtc": "2020-03-08T07:22:13Z",
  "obsTimeLocal": "2020-03-08 08:22:13",
  "neighborhood": "*********",
  "softwareType": "EasyWeatherV1.4.7",
  "country": "NL",
  "solarRadiation": 57.3,
  "lon": *.***,
  "realtimeFrequency": null,
  "epoch": 1583652133,
  "lat": **.****,
  "uv": 0,
  "winddir": 133,
  "humidity": 78,
  "qcStatus": 1,
  "metric": {
    "temp": 8.3,
    "heatIndex": 8.3,
    "dewpt": 4.7,
    "windChill": 8.3,
    "windSpeed": 4.7,
    "windGust": 7.2,
    "pressure": 1010.16,
    "precipRate": 0,
    "precipTotal": 0,
    "elev": 1.2
  }
}
![Screenshot_20200308-083822_Homey](https://user-images.githubusercontent.com/34476404/76158706-0a1d7200-6119-11ea-8e0f-095799579f5c.jpg)

**Comment by pjmpessers** [comment]
It is strange but i also don't see solar radiation in my homey insight. I see everything else but not solar radiation.

**Comment by AdyRock** [comment]
Thanks for the detailed report. It is very strange so will take some pondering to work out what is going wrong but I will get to the bottom of it.
As an aside I noticed I need a better icon for Solar Radiation, not sure why I didn't see that before 🤔

**Comment by pjmpessers** [comment]
Thank you. I will wait for the next update of this great app.

**Comment by AdyRock** [comment]
Could you email your StationID to me, ady@rockall.plus.com?
I can access it using my API key and it won't affect your usage. Hopefully that should mean that I get your UV and Radiation data which might help me track down the issue.

**Comment by AdyRock** [comment]
OK. It should now work.
Thanks for your help.

**Comment by pjmpessers** [comment]
Beautiful. You did it. It works great. Thank you. Very happy with it. And also better graphic.

Greetings: Pieter.

**Comment by AdyRock** [comment]
Hopefully it should show up in the Insights as well now.
I will leave this open for a few days just in case it's not there.

**Comment by pjmpessers** [comment]
On this moment solar radiation is not to be seen on homey insight. But for me not a problem. I'm very happy i can use solar radiation in a flow.

**Comment by pjmpessers** [comment]
I saw that you updated your app. I will try it tonight.

**Comment by pjmpessers** [comment]
Installed the new update and i know have "Solar radiation" in homey insight. Great. Thank you. This can be closed. 👍🏻

**Comment by AdyRock** [comment]
Excellent, thanks for letting me know and thanks for your help.
