### ISSUE TITLE
Double insight data readout for two readouts.

### ISSUE THREAD

**Issue by pjmpessers** [AdyRock/com.weatherunderground#5]
Hello Adyrock.

I see at homey insight there are two readouts that are the same.
"Feels like" and "feeling temperature"
"Temperature" and "warmth-index"
Is it possible to remove the double data collecting on homey insight? 
Thanks.

**Comment by AdyRock** [comment]
I am thinking I might remove both Heat Index and Wind Chill as they are used to calculate Feels Like based on the current temperature. So either one or neither is valid depending on the temperature.

WU sends both Wind Chill and Heat Index values but it then says that Feels Like is equal to Wind Chill if the temperature is 16.1C or below and it is equal to Heat Index when the temperature is 21 or over and it is equal to temperature when the temperature is between 16.1C and 21C. So the Feels like now uses those rules.

**Comment by pjmpessers** [comment]
Sounds good. 👍🏻

**Comment by AdyRock** [comment]
OK I have pushed, hopefully the last, test version. (0.1.6). This one removes the Wind Chill and Heat Index so you should see duplicate values in Insights.

**Comment by pjmpessers** [comment]
Great. Thank you. This can be closed as well and can be removed from to do-list. 😉

**Comment by AdyRock** [comment]
Thank you.
