### ISSUE TITLE
device values are not being displayed

### ISSUE THREAD

**Issue by Raycokes2000** [AdyRock/com.weatherunderground#6]
![Screenshot_20200310_204434_app homey](https://user-images.githubusercontent.com/51300944/76352930-2afbe800-6310-11ea-89d0-a2f482243938.jpg)
![Screenshot_20200310_203633_app homey](https://user-images.githubusercontent.com/51300944/76352934-2cc5ab80-6310-11ea-9432-f47170b259e0.jpg)
the actual device is not displaying any values. Do not see why, Rest is working properlay, forecast seems to be working okay. But device itself is not displaying info, see attachements

**Comment by Raycokes2000** [comment]
![Screenshot_20200310_204946_app homey](https://user-images.githubusercontent.com/51300944/76353315-c9884900-6310-11ea-9981-b6aab95e4b5d.jpg)

**Comment by AdyRock** [comment]
Have you tried deleting and adding the device again. Maybe where I have added and removed bits during the test versions I might have forgotten to add or remove something.

**Comment by AdyRock** [comment]
It seems your station is returning an error 204 No data found. When I look at it on WU I don't see any data in there either:
![image](https://user-images.githubusercontent.com/38184396/76356717-4cf46b00-630e-11ea-8f19-a6099ae3f560.png)
So has your station stopped sending data?

**Comment by Raycokes2000** [comment]
???? strange, we had some connection problems, but nothing changed in network. hope not its dying. ok need to look into that, thanks for looking into this

**Comment by AdyRock** [comment]
Looking at the graphs and table at the bottom of the WU page it seems your data has been intermittent for several days. But what is more strange is it seems to be getting pressure data still. Very confusing.

**Comment by AdyRock** [comment]
One good thing though is having a chance to get errors has helped me improve the error reporting that pops up at the top of the screen ;-)

**Comment by AdyRock** [comment]
New test version (0.1.7) that shows more descriptive error message than null ;-)

**Comment by Raycokes2000** [comment]
wierd indeed, it has data but not in homey still
![Knipsel](https://user-images.githubusercontent.com/51300944/76366393-23e1d380-632a-11ea-9dad-393deeeaefe0.JPG)

**Comment by pjmpessers** [comment]
Strange. It works great at my home. And i also have the alecto ws-5500. Did it worked before? Did you use the api-key? Not the device key.

**Comment by AdyRock** [comment]
It was still very intermittent around the time you posted so I guess it is just luck if Homey checks at the right time.
![image](https://user-images.githubusercontent.com/38184396/76397187-8c54a300-6372-11ea-9c14-a575649ea81e.png)
You can try adding my station (IHORSH12) with **your** API key to see if it works for that (it will use you allowance for daily accesses so don't keep it in for too long, hence I don't mind it being public here as it is freely available through the WU site anyway).

**Comment by pjmpessers** [comment]
I was so bold to connect your pws with my api-key to my homey. I hope i didn't break your trust. But i immediately got data from homey. So i doubt the problem is in the app.

**Comment by AdyRock** [comment]
When you go to the WU website the station ID is freely available for everyone to see so I don't see a problem with connecting to other stations. The access limit is based on your API key so in theory you can connect to multiple stations and just reduce the update frequency. Maybe I will look into that that at some point.

**Comment by pjmpessers** [comment]
That would be great. So that i can share the data of my pws to a friend that doesn't have a light sensor. When it went dark outside his lights also goes on at home instead of setting a flowcard:"when the sun goes down". That means it is too dark at his home.

**Comment by Raycokes2000** [comment]
hmm strane, more interruptions lately, need to fix that soon. It sat there for over 2 years now, no problems but now. Going to take it inside for further investigation

**Comment by pjmpessers** [comment]
Maybe low battery? If you want to try if it is a app problem try my pws. 

ITILBU34

**Comment by AdyRock** [comment]
One thing I am not sure of is if the failed requests increment the access count!
If I could take advantage of your misfortune would you look at the number for key usage?
This is on the API Key tab of your account on WU. There is a button for Show Usage and when you click on that it shows a graph of the usage count for each day. If it is around 1450 then it is counting the failures.
If it doesn't count the failures then I could retry at a higher frequency when it fails to try and catch any successful uploads.

**Comment by Raycokes2000** [comment]
used api key yes, can i just changed the device id with my own api key?

**Comment by Raycokes2000** [comment]
nice @pjmpessers bold move worked, i see data coming for device.
getting it inside for inspection and battery. api failure is robably not the issue, i asume for now hardware failure, i come back asap, thanks guys!

**Comment by AdyRock** [comment]
Yes, I checked the app with Pieters Station ID and yours while using my API key, which is how I found the errors.

So the count on your API key is around 1450?

**Comment by Raycokes2000** [comment]
yes 1476 tops, 1 a minute

**Comment by AdyRock** [comment]
Ok, thanks for confirmation. So increasing the frequency is not an option. 
Hope you can get your Station working again.

**Comment by pjmpessers** [comment]
I hope it is not hardware failure. Good luck raycokes.

**Comment by Raycokes2000** [comment]
I home it looks okay, wS is going outside asap. For now its closed
