### ISSUE TITLE
App is paused and acclamatiomark right corner of device

### ISSUE THREAD

**Issue by Raycokes2000** [AdyRock/com.weatherunderground#7]
App is paused and acclamatiomark right corner of device. More info following soon with printscreens

**Comment by Raycokes2000** [comment]
![Screenshot_20200316_195352_app homey](https://user-images.githubusercontent.com/51300944/76790977-2b88f880-67c0-11ea-861a-d9ec1f0d0337.jpg)
![Screenshot_20200316_195358_app homey](https://user-images.githubusercontent.com/51300944/76790997-3774ba80-67c0-11ea-86a3-8d76489cde89.jpg)

**Comment by Raycokes2000** [comment]
Last screen including te acclamatiomark is due to app nit running I gues
![Screenshot_20200316_195842_app homey](https://user-images.githubusercontent.com/51300944/76791234-b4079900-67c0-11ea-906a-b6d29d1ac8d9.jpg)

**Comment by Raycokes2000** [comment]
Yes it should be started and I started it again with no good result.
![Screenshot_20200316_200125_app homey](https://user-images.githubusercontent.com/51300944/76791384-12347c00-67c1-11ea-853e-2abafd918c61.jpg)

**Comment by pjmpessers** [comment]
Why are there 2 PWS? One from weather underground and one.......? Is this maybe a conflict? What if you remove alecto? Is your api-key over 1500 due double requests of both pws on same api-key?

**Comment by Raycokes2000** [comment]
One is device, second the forecast

**Comment by Raycokes2000** [comment]
Nope, apps is paused without user intervention. So no request made
![Screenshot_20200316_203903_com android chrome](https://user-images.githubusercontent.com/51300944/76793956-5c6c2c00-67c6-11ea-892c-65267ed631e0.jpg)

**Comment by pjmpessers** [comment]
Strange. Mine looks like this.
![Screenshot_20200316-205133_Homey](https://user-images.githubusercontent.com/34476404/76794802-1fa13480-67c8-11ea-9263-0640c5c3ab21.jpg)

**Comment by pjmpessers** [comment]
Do you use the right api-key? Api-key is 0 by you.

**Comment by AdyRock** [comment]
Is it possible you have the Log switched on?
That could either give me some information about the issue or it might be the issue. If it has been on for a while then it might be consuming too much memory. If possible, try opening the app configuration and clear the log to see if that fixes it.
Also try creating a diagnostics report as that will be sent to me. Sometimes it has useful information but not often so worth a try.

**Comment by Raycokes2000** [comment]
It is not strange with api request zero if app is paused for some reason ofcource. I check logging, took a while to switch it on cause app switched of really quick. Further info coming asap

**Comment by Raycokes2000** [comment]
Logging crashed app when trying to copy. Diag report 63fb7649-5660-4eb6-ae8e-7e11e1ab074c

**Comment by Raycokes2000** [comment]
Yes, took a few times, I have logging now
* https://api.weather.com/v2/pws/observations/current?numericPrecision=decimal&stationId=IARNHEM40&format=json&units=m&apiKey=94a311ba5af2404ba311ba5af2604be5
* retrieve data
* Done retrieval of data
* currentData = {
  "stationID": "IARNHEM40",
  "obsTimeUtc": "2020-03-16T21:06:43Z",
  "obsTimeLocal": "2020-03-16 22:06:43",
  "neighborhood": "Arnhem, Malburgen, Kamillelaan",
  "softwareType": "EasyWeatherV1.1.4",
  "country": "NL",
  "solarRadiation": 0,
  "lon": 5.921963,
  "realtimeFrequency": null,
  "epoch": 1584392803,
  "lat": 51.964474,
  "uv": 0,
  "winddir": 174,
  "humidity": 47,
  "qcStatus": 0,
  "metric": {
    "temp": 18.8,
    "heatIndex": 18.8,
    "dewpt": 7.3,
    "windChill": 18.8,
    "windSpeed": 0,
    "windGust": 0,
    "pressure": 1037.25,
    "precipRate": 0,
    "precipTotal": 0,
    "elev": 11.9
  }
}
* refreshCapabilities complete: SR= 0
* https://api.weather.com/v2/pws/observations/current?numericPrecision=decimal&stationId=IARNHEM40&format=json&units=m&apiKey=94a311ba5af2404ba311ba5af2604be5
* retrieve data
* Done retrieval of data
* currentData = {
  "stationID": "IARNHEM40",
  "obsTimeUtc": "2020-03-16T21:07:37Z",
  "obsTimeLocal": "2020-03-16 22:07:37",
  "neighborhood": "Arnhem, Malburgen, Kamillelaan",
  "softwareType": "EasyWeatherV1.1.4",
  "country": "NL",
  "solarRadiation": 0,
  "lon": 5.921963,
  "realtimeFrequency": null,
  "epoch": 1584392857,
  "lat": 51.964474,
  "uv": 0,
  "winddir": 174,
  "humidity": 47,
  "qcStatus": 0,
  "metric": {
    "temp": 18.8,
    "heatIndex": 18.8,
    "dewpt": 7.3,
    "windChill": 18.8,
    "windSpeed": 0,
    "windGust": 0,
    "pressure": 1037.59,
    "precipRate": 0,
    "precipTotal": 0,
    "elev": 11.9
  }
}
* refreshCapabilities complete: SR= 0

**Comment by AdyRock** [comment]
I deleted the log as it has your key in it.
All looks OK there though.
I also got the diagnostics report and that all looks OK as well.
Could you send a diagnostics report when the app has paused to see if it tells me why it paused.

**Comment by AdyRock** [comment]
Could you look on your insights to see if the app is using lots of memory or CPU. I have checked mine and it uses very little of either but just trying to get an idea of what is causing the problem.

**Comment by Raycokes2000** [comment]
Will do if happens again. Ok copy that, key is read only and can be change or reset easily but thanks.
I have some screenshots with CPU mem usage
![Screenshot_20200316_222300_com android chrome](https://user-images.githubusercontent.com/51300944/76801089-4154e880-67d5-11ea-84e6-a51f1f5478e8.jpg)
![Screenshot_20200316_222244_com android chrome](https://user-images.githubusercontent.com/51300944/76801099-45810600-67d5-11ea-9679-9d42911805c8.jpg)
![Screenshot_20200316_222230_com android chrome](https://user-images.githubusercontent.com/51300944/76801105-487bf680-67d5-11ea-8034-a26eac45518c.jpg)
![Screenshot_20200316_222217_com android chrome](https://user-images.githubusercontent.com/51300944/76801113-4ca81400-67d5-11ea-90a6-3551fcbc456f.jpg)
![Screenshot_20200316_222201_com android chrome](https://user-images.githubusercontent.com/51300944/76801121-503b9b00-67d5-11ea-9b6d-6007ae0dfbc9.jpg)

**Comment by AdyRock** [comment]
Wow, there are some high peaks there which could explain why it has been paused. I'm not sure why that would be as I don't see anything like that:
![image](https://user-images.githubusercontent.com/38184396/76801521-c0462300-67cd-11ea-832d-63e82fb1db03.png)
Was logging definitely switch off all the time?

**Comment by Raycokes2000** [comment]
A few days a had it on but it was not showing anything. Later I gues it paused because of that.

**Comment by AdyRock** [comment]
OK, hopefully it was just the logging filled up to much.
I have modified the code so the log auto clears after 5 kB so it can't run away if it is left on.
I will publish an update soon but also in the middle of testing a new trigger that fires if "Error 204 No data" is returned. That can be used to send a notification that the station has stopped sending data.

**Comment by AdyRock** [comment]
New version is now in test.

**Comment by Raycokes2000** [comment]
OK cool, what test link can not find it

**Comment by Raycokes2000** [comment]
https://homey.app/en-us/app/com.weatherunderground/Weather-Underground/test/
Yes.. At forum 👍

**Comment by AdyRock** [comment]
Is everything OK with this now so can I close the issue?

**Comment by pjmpessers** [comment]
No. The problem still excist. But i noticed something. They changed something in WU. When i look at the logging when i try to connect to my PWS i see that the adress is "https://api.weather.com/v3/location/search?query=ITILBU42&locationType=pws&language=en-US&format=json&apiKey=***********".
And as you can see in the adress it is version 3. When i place this adress in a webbrowser the message is:

{"errors":[{"error":{"code":"LOCATION-SERVICES:404","message":"The resource requested could not be located. Please verify the URL and try again later."}}]}

Now i connect to another PWS and with this the readout is fine and data is comming in. In the logging i see 

https://api.weather.com/v2/pws/observations/current?numericPrecision=decimal&stationId=ITILBURG76&format=json&units=m&apiKey=************

As you can see this is version V2 what WU is using. Now i tryed something. I change the URL back to my PWS. So it looked like:

https://api.weather.com/v2/pws/observations/current?numericPrecision=decimal&stationId=ITILBU42&format=json&units=m&apiKey=*************

And wow. This worked. I got:

{"observations":[{"stationID":"ITILBU42","obsTimeUtc":"2020-05-11T08:08:48Z","obsTimeLocal":"2020-05-11 10:08:48","neighborhood":"Tilburg","softwareType":"EasyWeatherV1.4.9","country":"NL","solarRadiation":613.8,"lon":5.087,"realtimeFrequency":null,"epoch":1589184528,"lat":51.548,"uv":5.0,"winddir":59,"humidity":43.0,"qcStatus":1,"metric":{"temp":10.3,"heatIndex":10.3,"dewpt":-1.7,"windChill":10.3,"windSpeed":8.7,"windGust":13.0,"pressure":1004.44,"precipRate":0.00,"precipTotal":0.30,"elev":16.5}}]}

So WU did something, Maybe a better security/firewall. But i think that everybody that gone install a new PWS on WU and are gone use your great app will be effected.

Have a safe day.

**Comment by Raycokes2000** [comment]
For me here no problem, low cpu, low memory etc, no problem

**Comment by pjmpessers** [comment]
Hello Ray. The problem is not on existing PWS. Only when you connect a new PWS. This will be done on a new URL V3. But there can be a possibility that also the connected PWS from the past will be changed to the new url V3. And then that could become a problem. But i'm not sure what WU will be doing.

**Comment by pjmpessers** [comment]
Try to connect to my PWS ITILBU42 and you will found out my problem. Don't forget to place back your station id.

**Comment by Raycokes2000** [comment]
close this topic, problem is solved, other problem needs other ticket ;-)

**Comment by Raycokes2000** [comment]
sorry pjmpessers, your reply was at refresh when i closed

**Comment by pjmpessers** [comment]
Sorry. You are right. My mistake.
