### ISSUE TITLE
Pressure is relative instead oplf absolute

### ISSUE THREAD

**Issue by Raycokes2000** [AdyRock/com.weatherunderground#9]
Hello Ady,

FYI, I noticed my station gives for air pressure the relative instead of absolute without notice. So it says just"presure" with mbar in the icon. But the number is shown is from the relative number. Is that known to you?

Regards Raymond

**Comment by AdyRock** [comment]
I will look into it as I'm not aware of the issue.

**Comment by AdyRock** [comment]
The WU data only has one pressure value reported and the description is as follows "Mean Sea Level Pressure, the equivalent pressure reading at sea level recorded at this station". The app just reports the value that it receives.
I can confirm that I am also seeing the relative value in the app but I can't remember if it was ever different to that.

**Comment by Raycokes2000** [comment]
Cool, sounds good, thanks for reply that fast 👍
